import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Header/Navbar";
import Footer from "./Components/Footer/Footer";
import Banner from "./Components/Header/Banner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-linear-to-b from-green-50 to-green-100 w-full px-4 sm:px-6 lg:px-8 mx-auto flex flex-col justify-between">
        <div className="flex flex-col flex-1">
          <Banner></Banner>

          {/* main section */}
          <main className="pt-16 pb-12 px-4 sm:px-6 lg:px-8 flex-1">{children}</main>
        </div>
        <footer>
        <Footer></Footer>
      </footer>
      </body>
      
    </html>
  );
}
